version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: nodeauthadmin
      POSTGRES_PASSWORD: nodeauthpassword
      POSTGRES_DB: nodeauthdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  nodeauthserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: