version: '3.8'

services:
  nodeauthpostgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # this port should not be exposed on production, use this for development only.
    ports:
      - 5433:5432
    networks:
      - nodeauthnetwork

  nodeauthserver:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - "3000:3000"
    depends_on:
      - nodeauthpostgres
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV}
      BASE_URL: ${BASE_URL}
      DEVELOPER_MODE_ENABLED: ${DEVELOPER_MODE_ENABLED}
      PERFORMANCE_TEST_ENABLED: ${PERFORMANCE_TEST_ENABLED}
      DEV_API_KEY: ${DEV_API_KEY}
      AUTH_REGISTER_ENABLED: ${AUTH_REGISTER_ENABLED}
      AUTH_LOGIN_ENABLED: ${AUTH_LOGIN_ENABLED}
      AUTH_LOGOUT_ENABLED: ${AUTH_LOGOUT_ENABLED}
      AUTH_REFRESH_ENABLED: ${AUTH_REFRESH_ENABLED}
      AUTH_FORGOT_PASSWORD_ENABLED: ${AUTH_FORGOT_PASSWORD_ENABLED}
      AUTH_RESET_PASSWORD_ENABLED: ${AUTH_RESET_PASSWORD_ENABLED}
      AUTH_VERIFY_EMAIL_ENABLED: ${AUTH_VERIFY_EMAIL_ENABLED}
      AUTH_VERIFY_PHONE_ENABLED: ${AUTH_VERIFY_PHONE_ENABLED}
      AUTH_CHANGE_PASSWORD_ENABLED: ${AUTH_CHANGE_PASSWORD_ENABLED}
      AUTH_PROFILE_ENABLED: ${AUTH_PROFILE_ENABLED}
      OAUTH_V1_AUTHORIZE_GET_ENABLED: ${OAUTH_V1_AUTHORIZE_GET_ENABLED}
      OAUTH_V1_TOKEN_ENABLED: ${OAUTH_V1_TOKEN_ENABLED}
      OAUTH_V1_REVOKE_ENABLED: ${OAUTH_V1_REVOKE_ENABLED}
      OAUTH_V1_INTROSPECT_ENABLED: ${OAUTH_V1_INTROSPECT_ENABLED}
      OAUTH_V1_USERINFO_ENABLED: ${OAUTH_V1_USERINFO_ENABLED}
      OAUTH_V1_ENDSESSION_ENABLED: ${OAUTH_V1_ENDSESSION_ENABLED}
      OAUTH_V1_REGISTER_ENABLED: ${OAUTH_V1_REGISTER_ENABLED}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      CSRF_SECRET: ${CSRF_SECRET}
      OTP_SECRET: ${OTP_SECRET}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING}
      DB_HOST_NAME: ${DB_HOST_NAME}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_PORT: ${DB_PORT}
      DB_CACERT: ${DB_CACERT}
      DB_DIALECT: ${DB_DIALECT}
    networks:
      - nodeauthnetwork
    command: sh -c "npx sequelize-cli db:migrate && npm run start"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodeauthserver
    networks:
      - nodeauthnetwork

networks:
  nodeauthnetwork:
    driver: bridge

volumes:
  postgres_data: {}